### ISSUE TITLE
question: what tool generate OPEN.xtrace files for Java programs / JVM?

### ISSUE THREAD

**Issue by monperrus** [spec-rgdevops/OPEN.xtrace#1]
what tools generate OPEN.xtrace files for Java programs?

Thanks --Martin

**Comment by okism** [comment]
Hi Martin,
Currently there are no tools generating data in this format. However, we developed adapters (open.xtrace.adapters) for some well known tools. You can run the available data through these adapters and they produce OPEN.xtrace. The adapter for Kieker (www.kieker-monitoring.net) is also able to work online, i.e., you can run it with the Kieker.Analysis, and it will produce OPEN.xtrace data.

Please let us know if we can help you further. You can find more information in our papers [2][3].

Best
Dušan

References:
[1] www.kieker-monitoring.net
[2] Dusan Okanovic, André van Hoorn, Christoph Heger, Alexander Wert, Stefan Siegl: Towards Performance Tooling Interoperability: An Open Format for Representing Execution Traces. EPEW 2016: 94-108
[3] Christoph Heger, André van Hoorn, Dusan Okanovic, Stefan Siegl, Alexander Wert: Expert-Guided Automatic Diagnosis of Performance Problems in Enterprise Applications. EDCC 2016: 185-188

**Comment by monperrus** [comment]
Thanks for your answer.

I'm trying the quickstart at http://kieker-monitoring.net/documentation/quickstart-guide/.

What's the configuration parameter to activate Open.xtrace output?

**Comment by okism** [comment]
There is no parameter for this.


Current use is as follows: You instrument the application with Kieker, and run it. Kieker will generate data in its own format into the storage, e.g., into a file. You can then run your analysis application, which calls KiekerTraceConverter.convertTraces(pathToKiekerDataFolder) method, and it will provide you with OPEN.xtrace data.


I hope I made it clearer for you. Unfortunately, we are struggling to find time to wrap it up properly for production use, but we hope to do it soon.


If you have more questions - ask away. We could also set up a Skype call.



________________________________

**Comment by monperrus** [comment]
Thanks for the explanation.

I'm quite impressed by the Kieker repository and would like to ask two questions:

- the issue tracker is closed: how do you handle bug reports and questions?
- do you welcome external contributions?

**Comment by okism** [comment]
Yes, Kieker has been around for quite some time.


For issue tracking JIRA is used. Here is the link (https://kieker-monitoring.atlassian.net/), and here is a brief info on this topic (http://kieker-monitoring.net/support/). Using the first link you can also access our Confluence wiki.


External contributions are welcome.

________________________________

**Comment by monperrus** [comment]
Thanks Dušan.

See https://github.com/kieker-monitoring/kieker/pull/177

**Comment by okism** [comment]
Thanks Martin, very nice of you! My colleagues in charge of Kieker development will handle it.


I hope this is not the only external contribution you had in mind [😊]

________________________________
